return {
  {
    "catppuccin/nvim",
    config = function()
      local mocha = require("catppuccin.palettes").get_palette("mocha")

      require("catppuccin").setup({
        color_overrides = {
          macchiato = { -- purple
            rosewater = "#f5e0dc",
            flamingo = "#f2cdcd",
            pink = "#f5c2e7",
            mauve = "#cba6f7",
            red = "#f38ba8",
            maroon = "#eba0ac",
            peach = "#fab387",
            yellow = "#f9e2af",
            green = "#a6e3a1",
            teal = "#94e2d5",
            sky = "#89dceb",
            sapphire = "#74c7ec",
            blue = "#89b4fa",
            lavender = "#b4befe",
            text = "#fdd6f4",
            subtext1 = "#dac2de",
            subtext0 = "#c6adc8",
            overlay2 = "#b399b2",
            overlay1 = "#9f849c",
            overlay0 = "#7c7086",
            surface2 = "#705b70",
            surface1 = "#5a475a",
            surface0 = "#443244",
            base = "#2e1e2e",
            mantle = "#251825",
            crust = "#1b111b",
          },
          frappe = { -- grey
            rosewater = "#f5e0dc",
            flamingo = "#f2cdcd",
            pink = "#f5c2e7",
            mauve = "#cba6f7",
            red = "#f38ba8",
            maroon = "#eba0ac",
            peach = "#fab387",
            yellow = "#f9e2af",
            green = "#a6e3a1",
            teal = "#94e2d5",
            sky = "#89dceb",
            sapphire = "#74c7ec",
            blue = "#89b4fa",
            lavender = "#b4befe",
            text = "#fdf6f4",
            subtext1 = "#dad2de",
            subtext0 = "#c6cdc8",
            overlay2 = "#b3b9b2",
            overlay1 = "#9f949c",
            overlay0 = "#7c7086",
            surface2 = "#707070",
            surface1 = "#5a5a5a",
            surface0 = "#444444",
            base = "#2e2e2e",
            mantle = "#252525",
            crust = "#1b1b1b",
          },
          latte = { -- green
            rosewater = "#f5e0dc",
            flamingo = "#f2cdcd",
            pink = "#f5c2e7",
            mauve = "#cba6f7",
            red = "#f38ba8",
            maroon = "#eba0ac",
            peach = "#fab387",
            yellow = "#f9e2af",
            green = "#a6e3a1",
            teal = "#94e2d5",
            sky = "#89dceb",
            sapphire = "#74c7ec",
            blue = "#89b4fa",
            lavender = "#b4befe",
            text = "#cdf6f4",
            subtext1 = "#bad2de",
            subtext0 = "#a6cdc8",
            overlay2 = "#93b9b2",
            overlay1 = "#7f949c",
            overlay0 = "#6c8086",
            surface2 = "#587b70",
            surface1 = "#45575a",
            surface0 = "#314244",
            base = "#1e2e2e",
            mantle = "#182525",
            crust = "#111b1b",
          }
        }
      })
      vim.cmd.colorscheme "catppuccin-mocha"
    end
  },
  { "sainnhe/sonokai" },
}

